# OpenRouter API Configuration
api_key: "your-openrouter-api-key-here"
model: "openai/gpt-3.5-turbo"  # Default model
type: "openrouter"

# Model Parameters
temperature: 0.7
top_p: 0.9
frequency_penalty: 0.0
min_p: 0.0
presence_penalty: 0.0
repetition_penalty: 0.0
top_a: 0.0
top_k: 0.0

# API Limits
api_requests_per_minute: 60
api_tokens_per_minute: 100000
api_tokens_per_day: 1000000
api_concurrent_requests: 5

# GCRA Rate Limiting Configuration (Optional)
# Format: {model_name: {limit: int, window: int, burst: int}}
gcra_requests_limit:
  "openai/gpt-3.5-turbo":
    limit: 40          # 40 requests
    window: 60         # per 60 seconds
    burst: 5           # Allow burst of 5 requests
  "openai/gpt-4":
    limit: 10          # 10 requests 
    window: 60         # per 60 seconds
    burst: 2           # Allow burst of 2 requests

gcra_tokens_limit:
  "openai/gpt-3.5-turbo":
    limit: 80000       # 80,000 tokens
    window: 60         # per 60 seconds
    burst: 10000       # Allow burst of 10,000 tokens
  "openai/gpt-4":
    limit: 30000       # 30,000 tokens
    window: 60         # per 60 seconds
    burst: 5000        # Allow burst of 5,000 tokens

# Bot Configuration
max_tokens: 2000
bot_language: "English"
base_url: "https://openrouter.ai/api/v1"
assistant_prompt: "You are a helpful assistant."

# Budget Configuration
budget_period: "monthly"
guest_budget: 0.0
user_budget: 5.0

# User Access Configuration
admin_ids: "192599414" # Replace with actual admin chat IDs
allowed_user_ids: ""    # Comma-separated list of allowed user IDs
allowed_group_ids: ""   # Comma-separated list of allowed group IDs

# History Configuration
max_history_size: 10
max_history_time: 60

# Vision Configuration
vision: "false"
vision_prompt: ""
vision_detail: "auto"

# Stats Configuration
stats_min_role: "user"

# Language Configuration
lang: "en"
