services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./user_data:/app/user_data
    env_file:
      - .env
    restart: unless-stopped